### ISSUE TITLE
Artificial intelligence for automatic diagnosis of biliary stricture malignancy status in single-operator cholangioscopy: a pilot study

### ISSUE THREAD

**Issue by MoaazAlneasan** [AstraBert/BioMedicalPapersBot#1]

**Comment by MoaazAlneasan** [comment]
Artificial intelligence for automatic diagnosis of biliary stricture malignancy status in single-operator cholangioscopy: a pilot study

**Comment by AstraBert** [comment]
Dear @MoaazAlneasan, could you explain more in-depth the issue that you are encountering?
